# Generated by Django 3.0.2 on 2020-01-13 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_duration', models.IntegerField(blank=True, null=True)),
                ('pref_time_of_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TimeOfDay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RunningProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_volume', models.IntegerField(blank=True, null=True)),
                ('avg_pace', models.DurationField(null=True)),
                ('pref_time_of_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TimeOfDay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RidingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_volume', models.IntegerField(blank=True, null=True)),
                ('flat_avg', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('hill_avg', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pref_time_of_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TimeOfDay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
