# Generated by Django 3.0.2 on 2020-01-13 11:46

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningprofile',
            name='avg_pace',
            field=app.models.MinSecDurationField(null=True),
        ),
    ]
