# Generated by Django 3.0.2 on 2020-01-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
