# Generated by Django 3.0.2 on 2020-01-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200115_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
