# Generated by Django 3.0.2 on 2020-01-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_directmessage_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ridingprofile',
            options={'ordering': ['pref_time_of_day']},
        ),
        migrations.AlterModelOptions(
            name='runningprofile',
            options={'ordering': ['pref_time_of_day']},
        ),
        migrations.AlterModelOptions(
            name='workoutprofile',
            options={'ordering': ['pref_time_of_day']},
        ),
    ]
