# Generated by Django 3.0.2 on 2020-01-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200115_1913'),
        ('app', '0007_auto_20200115_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=4)),
                ('elevation', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(null=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Profile')),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
    ]
