# Generated by Django 3.0.2 on 2020-01-13 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='user_pics')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
